### ISSUE TITLE
could not find SOAP::Client

### ISSUE THREAD

**Issue by jeffythedragonslayer** [retupmoca/P6-SOAP#7]
How do I get this to look for the pm6 file?

$ perl6 test.pl6
===SORRY!===
Could not find SOAP::Client at line 1 in:
    /home/development/.perl6
    /usr/lib/perl6/site
    /usr/lib/perl6/vendor
    /usr/lib/perl6
    CompUnit::Repository::AbsolutePath<93888999975024>
    CompUnit::Repository::NQP<93888979764392>
    CompUnit::Repository::Perl5<93888979764432>

**Comment by JJ** [comment]
Please try:

    raku -Ilib test.pl6

as long as you're in the root directory. Alternatively, `zef install .` and then do the same (please observe that `raku` is now preferred to `perl6`, although both work.
